// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLxlGOIOeXi7va6hwd01G8EyAzxhGZ59I',
    appId: '1:61371515180:web:4d9797f438500d6ef42c89',
    messagingSenderId: '61371515180',
    projectId: 'es-pi3-2026-t3-g15',
    authDomain: 'es-pi3-2026-t3-g15.firebaseapp.com',
    storageBucket: 'es-pi3-2026-t3-g15.firebasestorage.app',
    measurementId: 'G-C44DXFP6T5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkn1_huTzu0tPUlSU0BXRor0W6-gHGEPM',
    appId: '1:61371515180:android:4849243d85d3e61af42c89',
    messagingSenderId: '61371515180',
    projectId: 'es-pi3-2026-t3-g15',
    storageBucket: 'es-pi3-2026-t3-g15.firebasestorage.app',
  );
}
